spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch?rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: always  # Creates batch tables on startup
    job:
      enabled: false